pingpong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('standings.urls')),
]

standings/urls.py
from django.urls import path
from . import views

app_name = 'standings'

urlpatterns = [
    path('pingpong/', views.PingPongIndexView.as_view(), name='pindex'),
    path('pingpong/elo/', views.PingPongIndexView.as_view(), name='elo'),
    path('create/', views.create, name='create'),
    path('pingpong/games/', views.GamesView.as_view(), name='games'),
    path('pingpong/<player>/', views.PlayerView.as_view(), name='player'),
    path('cut/', views.cut_cards, name='cut'),
    path('', views.CardIndexView.as_view(), name='cindex'),

]

standings/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta, datetime

class Player(models.Model):
    name = models.CharField(max_length=200, unique=True)
    id = models.CharField(max_length=200, primary_key=True)
    elo = models.IntegerField(default=1500)
    def __str__(self):
        return self.name
    def cards_count_year(self):
        yr = datetime(2020, 9, 1, 0, 0, 0, tzinfo=timezone.utc)
        return self.cards.filter(date__gt=yr).count()

class Card(models.Model):
    cutter = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="cards")
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Cut by {self.cutter} on {self.date}"

class Game(models.Model):
    winner = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="winners")
    winner_points = models.IntegerField(default=0)
    loser = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="losers")
    loser_points = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.winner.name + " beat " + self.loser.name
    def save(self, *args, **kwargs):
        if not self.pk:
            if self.winner.name == self.loser.name:
                return
            recalculate_elo(self.winner, self.loser)
        super(Game, self).save(*args, **kwargs)

def recalculate_elo(winner, loser, wk=24, lk=24):
    w = winner.elo
    l = loser.elo
    wg = winner.losers.count() + winner.winners.count()
    lg = loser.losers.count() + loser.winners.count()
    if wg <= 10:
        wk = 36
    if lg <= 10:
        lk = 36
    d = (w-l)/400
    we = 1 / (1 + 10**(-d))
    le = 1 / (1 + 10**(d))
    winner.elo = w + max(1, wk*(1-we))
    loser.elo = l - max(1, lk*le)
    winner.save()
    loser.save()

# Create your models here.

standings/views.py
import re, requests
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.template import loader
from .models import Player, Game, Card
from django.db.models import Count, Q, Sum
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timedelta
from django.utils import timezone
from .slack_webhooks import CARDS_WEBHOOK

# Create your views here.

class CardIndexView(generic.ListView):
    template_name = 'standings/cindex.html'
    context_object_name = 'standings'
    def get_queryset(self):
        yr = datetime(2020, 9, 1, 0, 0, 0, tzinfo=timezone.utc)
        return Player.objects.annotate(cards_cut=Count('cards', filter=Q(cards__date__gt=yr))).filter(cards_cut__gt=0).order_by('-cards_cut')


class PingPongIndexView(generic.ListView):
    template_name = 'standings/pindex.html'
    context_object_name = 'standings'
    def get_queryset(self):
        return Player.objects.annotate(wins=Count('winners', distinct=True), losses=Count('losers', distinct=True)).order_by('-elo')

class GamesView(generic.ListView):
    template_name = 'standings/games.html'
    context_object_name = 'games'
    def get_queryset(self):
        return Game.objects.order_by('-date')


class PlayerView(generic.ListView):
    template_name = 'standings/games_player.html'
    context_object_name = 'games'
    def get_queryset(self):
        player = Player.objects.get(name=self.kwargs['player'])
        return Game.objects.filter(Q(winner=player) | Q(loser=player)).order_by('-date')
    def get_context_data(self):
        context = super().get_context_data(**self.kwargs)
        context['player'] = self.kwargs['player']
        return context

@csrf_exempt
def cut_cards(request):
    if request.method == "GET":
        return redirect('standings:cindex')
    if request.method == "POST":
        command = request.POST.get('command')
    if command == "/cards":
        text = request.POST.get('text')
        try:
            val = int(text)
        except:
            medals = {1: ':first_place_medal:', 2: ':second_place_medal:', 3: ':third_place_medal:'}
            yr = datetime(2020, 9, 1, 0, 0, 0, tzinfo=timezone.utc)
            card_cutters = Player.objects.annotate(cards_cut=Count('cards', filter=Q(cards__date__gt=yr))).filter(cards_cut__gt=0).order_by('-cards_cut')
            message = "No one has cut any cards!  Start cutting cards ..."
            if len(card_cutters):
                message = f"*TOTAL CARDS CUT THIS YEAR: {Card.objects.filter(date__gt=yr).count()}*\n" + "\n".join([f"{medals.get(i+1, i+1)} {player.name} ({player.cards_cut})" for i, player in enumerate(card_cutters)])
            tn = datetime.now(tz=timezone.utc)-timedelta(7)
            card_cutters_w = Player.objects.annotate(cards_cut=Count('cards', filter=Q(cards__date__gt=tn))).filter(cards_cut__gt=0).order_by('-cards_cut')
            message_w = f"\nNo one has cut any cards since {tn.strftime('%m/%d/%Y')}!  Start cutting cards ..."
            if len(card_cutters_w):
                message_w = f"\n*CARDS CUT SINCE {tn.strftime('%m/%d/%Y')}: {Card.objects.filter(date__gt=tn).count()}*\n" + "\n".join([f"{medals.get(i+1, i+1)} {player.name} ({player.cards_cut})" for i, player in enumerate(card_cutters_w)])
            return JsonResponse({"response_type": "in_channel", "text": message + message_w})
        p, new = Player.objects.get_or_create(id=request.POST['user_id'])
        p.name = request.POST['user_name']
        p.save()
        if val > 0:
            for x in range(val):
                Card.objects.create(cutter=p)
            p.save()
            message = f"{p.name} cut {val} cards.  {p.name} now has cut a total of {p.cards_count_year()} cards this year."
            webhook_url = CARDS_WEBHOOK
            requests.post(webhook_url, json={'text': message})
        elif val + p.cards.count() >= 0:
            Card.objects.filter(id__in=list(p.cards.order_by('-date').values_list('pk', flat=True)[:-val])).delete()
            message = f"You subtracted {-val} cards from your total.  You now have cut a total of {p.cards_count_year()} cards."
        else:
            c = p.cards_count_year()
            p.cards.all().delete()
            message = f"You had {c} cards ... but you tried to subtract {-val}.  Your total number of cards cut has instead been set to zero."
        return JsonResponse({"response_type": "ephemeral", "text": message})
    return HttpResponse("You did something wrong.")


@csrf_exempt
def create(request):
    if request.method == "GET":
        return redirect('standings:pindex')
    if request.method == "POST":
        command = request.POST.get('command')
        if command == "/add":
            text = request.POST['text']
            try:
                info = re.search(r"<@(?P<id>.*?)\|(?P<name>.*?)>", text).groupdict()
            except AttributeError:
                return HttpResponse("That didn't work. Try `/add @player`")
            p, new = Player.objects.get_or_create(id=info['id'])
            p.name = info['name']
            p.save()
            return JsonResponse({"response_type": "in_channel", "text": f"{p.name} ({p.elo})"})
        if command == "/update":
            text = request.POST['text']
            try:
                info = re.search(r"<@(?P<id>.*?)\|(?P<name>.*?)> (?P<elo>[0-9]*)", text).groupdict()
            except AttributeError:
                return HttpResponse("That didn't work. Try `/update @player 1500`")
            p, new = Player.objects.get_or_create(id=info['id'])
            p.name = info['name']
            p.elo = info['elo']
            p.save()
            return JsonResponse({"response_type": "in_channel", "text": f"{p.name} ({p.elo})"})

        if command == "/game":
            text = request.POST['text']
            try:
                info = re.search(r"<@(?P<w_id>.*?)\|(?P<w_name>.*?)> <@(?P<l_id>.*?)\|(?P<l_name>.*?)>", text).groupdict()
            except AttributeError:
                return HttpResponse("That didn't work. Try `/game @winner @loser`")
            w, new = Player.objects.get_or_create(id=info['w_id'])
            w.name = info['w_name']
            w.save()
            l, new = Player.objects.get_or_create(id=info['l_id'])
            l.name = info['l_name']
            l.save()
            Game.objects.create(winner=w, loser=l)
            return JsonResponse({"response_type": "in_channel", "text": f"{w.name} beats {l.name}"})
        if command == "/standings":
            return JsonResponse({"response_type": "in_channel", "text": "\n".join([f"{i+1}. {player.name} ({player.elo})" for i, player in enumerate(Player.objects.order_by('-elo'))])})
        return HttpResponse("You did something wrong.")

standings/templates/standings/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>WC Debate Ping Pong - {% block title %}Home{% endblock %}</title>
</head>

<body>
    <div id="content">
<h1><a href="{% url 'standings:cindex' %}">Cards</a> <a href="{% url 'standings:pindex' %}">Standings</a> <a href="{% url 'standings:games' %}">Games</a></h1>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

standings/templates/standings/cindex.html
{% extends "standings/base.html" %}
{% block content %}

<table>
  <tr>
    <th>Name</th>
    <th>Cards Cut</th>
  </tr>
{% for player in standings %}  
  <tr>
    <td>{{ player.name }}</td>
    <td>{{ player.cards_count_year }}</td>
  </tr>
{% empty %}
  <tr>
    <td></td>
    <td></td>
  </tr>
{% endfor %}
</table>
{% endblock %}

standings/templates/standings/games.html
{% extends "standings/base.html" %}
{% block title %}Games{% endblock %}

{% block content %}

<table>
  <tr>
    <th>Winner</th>
    <th>Score</th>
    <th>Loser</th>
    <th>Date</th>
  </tr>
{% for game in games %}
  <tr>
    <td><a href="{% url 'standings:player' game.winner.name %}">{{ game.winner.name }}</a></td>
    <td>{{ game.winner_points }} - {{ game.loser_points }}</td>
    <td><a href="{% url 'standings:player' game.loser.name %}">{{ game.loser.name }}</a></td>
    <td>{{ game.date }}</td>
  </tr>
{% empty %}
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
{% endfor %}
</table>
{% endblock %}

standings/templates/standings/games_player.html
{% extends "standings/base.html" %}
{% block title %}{{ player }} Games{% endblock %}
{% block content %}

<table>
  <tr>
    <th>Winner</th>
    <th>Score</th>
    <th>Loser</th>
    <th>Date</th>
  </tr>
{% for game in games %}
  <tr>
    <td><a href="{% url 'standings:player' game.winner.name %}">{{ game.winner.name }}</a></td>
    <td>{{ game.winner_points }} - {{ game.loser_points }}</td>
    <td><a href="{% url 'standings:player' game.loser.name %}">{{ game.loser.name }}</a></td>
    <td>{{ game.date }}</td>
  </tr>
{% empty %}
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
{% endfor %}
</table>
{% endblock %}

standings/templates/standings/pindex.html
{% extends "standings/base.html" %}
{% block content %}

<table>
  <tr>
    <th>Name</th>
    <th>Wins</th>
    <th>Losses</th>
    <th>ELO</th>
  </tr>
{% for player in standings %}  
  <tr>
    <td><a href="{% url 'standings:player' player.name %}">{{ player.name }}</a></td>
    <td>{{ player.wins }}</td>
    <td>{{ player.losses }}</td>
    <td>{{ player.elo }}</td>
  </tr>
{% empty %}
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
{% endfor %}
</table>
{% endblock %}